{
   "CVE_data_meta" : {
      "ASSIGNER" : "sfowler@redhat.com",
      "ID" : "CVE-2018-1061",
      "STATE" : "PUBLIC"
   },
   "affects" : {
      "vendor" : {
         "vendor_data" : [
            {
               "product" : {
                  "product_data" : [
                     {
                        "product_name" : "python",
                        "version" : {
                           "version_data" : [
                              {
                                 "version_value" : "python 2.7.15"
                              },
                              {
                                 "version_value" : "python 3.4.9"
                              },
                              {
                                 "version_value" : "python 3.5.6"
                              },
                              {
                                 "version_value" : "python 3.7.0"
                              }
                           ]
                        }
                     }
                  ]
               },
               "vendor_name" : "[UNKNOWN]"
            }
         ]
      }
   },
   "data_format" : "MITRE",
   "data_type" : "CVE",
   "data_version" : "4.0",
   "description" : {
      "description_data" : [
         {
            "lang" : "eng",
            "value" : "python before versions 2.7.15, 3.4.9, 3.5.6rc1, 3.6.5rc1 and 3.7.0 is vulnerable to catastrophic backtracking in the difflib.IS_LINE_JUNK method.  An attacker could use this flaw to cause denial of service."
         }
      ]
   },
   "impact" : {
      "cvss" : [
         [
            {
               "vectorString" : "6.5/CVSS:3.0/AV:N/AC:L/PR:N/UI:R/S:U/C:N/I:N/A:H",
               "version" : "3.0"
            }
         ]
      ]
   },
   "problemtype" : {
      "problemtype_data" : [
         {
            "description" : [
               {
                  "lang" : "eng",
                  "value" : "CWE-20"
               }
            ]
         }
      ]
   },
   "references" : {
      "reference_data" : [
         {
            "name" : "[debian-lts-announce] 20180925 [SECURITY] [DLA 1519-1] python2.7 security update",
            "refsource" : "MLIST",
            "url" : "https://lists.debian.org/debian-lts-announce/2018/09/msg00030.html"
         },
         {
            "name" : "[debian-lts-announce] 20180926 [SECURITY] [DLA 1520-1] python3.4 security update",
            "refsource" : "MLIST",
            "url" : "https://lists.debian.org/debian-lts-announce/2018/09/msg00031.html"
         },
         {
            "name" : "https://bugs.python.org/issue32981",
            "refsource" : "CONFIRM",
            "url" : "https://bugs.python.org/issue32981"
         },
         {
            "name" : "https://bugzilla.redhat.com/show_bug.cgi?id=CVE-2018-1061",
            "refsource" : "CONFIRM",
            "url" : "https://bugzilla.redhat.com/show_bug.cgi?id=CVE-2018-1061"
         },
         {
            "name" : "https://docs.python.org/3.5/whatsnew/changelog.html#python-3-5-6-release-candidate-1",
            "refsource" : "CONFIRM",
            "url" : "https://docs.python.org/3.5/whatsnew/changelog.html#python-3-5-6-release-candidate-1"
         },
         {
            "name" : "https://docs.python.org/3.6/whatsnew/changelog.html#python-3-6-5-release-candidate-1",
            "refsource" : "CONFIRM",
            "url" : "https://docs.python.org/3.6/whatsnew/changelog.html#python-3-6-5-release-candidate-1"
         },
         {
            "name" : "DSA-4306",
            "refsource" : "DEBIAN",
            "url" : "https://www.debian.org/security/2018/dsa-4306"
         },
         {
            "name" : "DSA-4307",
            "refsource" : "DEBIAN",
            "url" : "https://www.debian.org/security/2018/dsa-4307"
         },
         {
            "name" : "RHSA-2018:3041",
            "refsource" : "REDHAT",
            "url" : "https://access.redhat.com/errata/RHSA-2018:3041"
         },
         {
            "name" : "RHSA-2018:3505",
            "refsource" : "REDHAT",
            "url" : "https://access.redhat.com/errata/RHSA-2018:3505"
         },
         {
            "name" : "USN-3817-1",
            "refsource" : "UBUNTU",
            "url" : "https://usn.ubuntu.com/3817-1/"
         },
         {
            "name" : "USN-3817-2",
            "refsource" : "UBUNTU",
            "url" : "https://usn.ubuntu.com/3817-2/"
         },
         {
            "name" : "1042001",
            "refsource" : "SECTRACK",
            "url" : "http://www.securitytracker.com/id/1042001"
         }
      ]
   }
}
