{
    "CVE_data_meta": {
        "ASSIGNER": "cve@mitre.org",
        "ID": "CVE-2016-9398",
        "STATE": "PUBLIC"
    },
    "affects": {
        "vendor": {
            "vendor_data": [
                {
                    "product": {
                        "product_data": [
                            {
                                "product_name": "n/a",
                                "version": {
                                    "version_data": [
                                        {
                                            "version_value": "n/a"
                                        }
                                    ]
                                }
                            }
                        ]
                    },
                    "vendor_name": "n/a"
                }
            ]
        }
    },
    "data_format": "MITRE",
    "data_type": "CVE",
    "data_version": "4.0",
    "description": {
        "description_data": [
            {
                "lang": "eng",
                "value": "The jpc_floorlog2 function in jpc_math.c in JasPer before 1.900.17 allows remote attackers to cause a denial of service (assertion failure) via unspecified vectors."
            }
        ]
    },
    "problemtype": {
        "problemtype_data": [
            {
                "description": [
                    {
                        "lang": "eng",
                        "value": "n/a"
                    }
                ]
            }
        ]
    },
    "references": {
        "reference_data": [
            {
                "name": "[oss-security] 20161117 Re: jasper: multiple assertion failures",
                "refsource": "MLIST",
                "url": "http://www.openwall.com/lists/oss-security/2016/11/17/1"
            },
            {
                "name": "https://blogs.gentoo.org/ago/2016/11/16/jasper-multiple-assertion-failure",
                "refsource": "MISC",
                "url": "https://blogs.gentoo.org/ago/2016/11/16/jasper-multiple-assertion-failure"
            },
            {
                "name": "https://bugzilla.redhat.com/show_bug.cgi?id=1396980",
                "refsource": "CONFIRM",
                "url": "https://bugzilla.redhat.com/show_bug.cgi?id=1396980"
            },
            {
                "name": "SUSE-SU-2017:0084",
                "refsource": "SUSE",
                "url": "http://lists.opensuse.org/opensuse-security-announce/2017-01/msg00008.html"
            },
            {
                "name": "openSUSE-SU-2017:0101",
                "refsource": "SUSE",
                "url": "http://lists.opensuse.org/opensuse-security-announce/2017-01/msg00009.html"
            },
            {
                "name": "94382",
                "refsource": "BID",
                "url": "http://www.securityfocus.com/bid/94382"
            }
        ]
    }
}