{
   "CVE_data_meta" : {
      "ASSIGNER" : "psampaio@redhat.com",
      "ID" : "CVE-2018-14647",
      "STATE" : "PUBLIC"
   },
   "affects" : {
      "vendor" : {
         "vendor_data" : [
            {
               "product" : {
                  "product_data" : [
                     {
                        "product_name" : "Python",
                        "version" : {
                           "version_data" : [
                              {
                                 "version_value" : "3.8, 3.7, 3.6, 3.5, 3.4, 2.7"
                              }
                           ]
                        }
                     }
                  ]
               },
               "vendor_name" : "The Python Project"
            }
         ]
      }
   },
   "data_format" : "MITRE",
   "data_type" : "CVE",
   "data_version" : "4.0",
   "description" : {
      "description_data" : [
         {
            "lang" : "eng",
            "value" : "Python's elementtree C accelerator failed to initialise Expat's hash salt during initialization. This could make it easy to conduct denial of service attacks against Expat by constructing an XML document that would cause pathological hash collisions in Expat's internal data structures, consuming large amounts CPU and RAM. Python 3.8, 3.7, 3.6, 3.5, 3.4, 2.7 are believed to be vulnerable."
         }
      ]
   },
   "impact" : {
      "cvss" : [
         [
            {
               "vectorString" : "5.3/CVSS:3.0/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:L",
               "version" : "3.0"
            }
         ]
      ]
   },
   "problemtype" : {
      "problemtype_data" : [
         {
            "description" : [
               {
                  "lang" : "eng",
                  "value" : "CWE-665"
               }
            ]
         },
         {
            "description" : [
               {
                  "lang" : "eng",
                  "value" : "CWE-335"
               }
            ]
         }
      ]
   },
   "references" : {
      "reference_data" : [
         {
            "name" : "https://bugs.python.org/issue34623",
            "refsource" : "MISC",
            "url" : "https://bugs.python.org/issue34623"
         },
         {
            "name" : "https://bugzilla.redhat.com/show_bug.cgi?id=CVE-2018-14647",
            "refsource" : "CONFIRM",
            "url" : "https://bugzilla.redhat.com/show_bug.cgi?id=CVE-2018-14647"
         },
         {
            "name" : "DSA-4306",
            "refsource" : "DEBIAN",
            "url" : "https://www.debian.org/security/2018/dsa-4306"
         },
         {
            "name" : "DSA-4307",
            "refsource" : "DEBIAN",
            "url" : "https://www.debian.org/security/2018/dsa-4307"
         },
         {
            "name" : "USN-3817-1",
            "refsource" : "UBUNTU",
            "url" : "https://usn.ubuntu.com/3817-1/"
         },
         {
            "name" : "USN-3817-2",
            "refsource" : "UBUNTU",
            "url" : "https://usn.ubuntu.com/3817-2/"
         },
         {
            "name" : "105396",
            "refsource" : "BID",
            "url" : "http://www.securityfocus.com/bid/105396"
         },
         {
            "name" : "1041740",
            "refsource" : "SECTRACK",
            "url" : "http://www.securitytracker.com/id/1041740"
         }
      ]
   }
}
