{
   "CVE_data_meta" : {
      "ASSIGNER" : "cve@mitre.org",
      "ID" : "CVE-2016-4000",
      "STATE" : "PUBLIC"
   },
   "affects" : {
      "vendor" : {
         "vendor_data" : [
            {
               "product" : {
                  "product_data" : [
                     {
                        "product_name" : "n/a",
                        "version" : {
                           "version_data" : [
                              {
                                 "version_value" : "n/a"
                              }
                           ]
                        }
                     }
                  ]
               },
               "vendor_name" : "n/a"
            }
         ]
      }
   },
   "data_format" : "MITRE",
   "data_type" : "CVE",
   "data_version" : "4.0",
   "description" : {
      "description_data" : [
         {
            "lang" : "eng",
            "value" : "Jython before 2.7.1rc1 allows attackers to execute arbitrary code via a crafted serialized PyFunction object."
         }
      ]
   },
   "problemtype" : {
      "problemtype_data" : [
         {
            "description" : [
               {
                  "lang" : "eng",
                  "value" : "n/a"
               }
            ]
         }
      ]
   },
   "references" : {
      "reference_data" : [
         {
            "name" : "https://security-tracker.debian.org/tracker/CVE-2016-4000",
            "refsource" : "MISC",
            "url" : "https://security-tracker.debian.org/tracker/CVE-2016-4000"
         },
         {
            "name" : "https://snyk.io/vuln/SNYK-JAVA-ORGPYTHON-31451",
            "refsource" : "MISC",
            "url" : "https://snyk.io/vuln/SNYK-JAVA-ORGPYTHON-31451"
         },
         {
            "name" : "http://bugs.jython.org/issue2454",
            "refsource" : "CONFIRM",
            "url" : "http://bugs.jython.org/issue2454"
         },
         {
            "name" : "https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=864859",
            "refsource" : "CONFIRM",
            "url" : "https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=864859"
         },
         {
            "name" : "https://hg.python.org/jython/file/v2.7.1rc1/NEWS",
            "refsource" : "CONFIRM",
            "url" : "https://hg.python.org/jython/file/v2.7.1rc1/NEWS"
         },
         {
            "name" : "https://hg.python.org/jython/rev/d06e29d100c0",
            "refsource" : "CONFIRM",
            "url" : "https://hg.python.org/jython/rev/d06e29d100c0"
         },
         {
            "name" : "http://www.oracle.com/technetwork/security-advisory/cpuoct2018-4428296.html",
            "refsource" : "CONFIRM",
            "url" : "http://www.oracle.com/technetwork/security-advisory/cpuoct2018-4428296.html"
         },
         {
            "name" : "DSA-3893",
            "refsource" : "DEBIAN",
            "url" : "http://www.debian.org/security/2017/dsa-3893"
         },
         {
            "name" : "GLSA-201710-28",
            "refsource" : "GENTOO",
            "url" : "https://security.gentoo.org/glsa/201710-28"
         },
         {
            "name" : "105647",
            "refsource" : "BID",
            "url" : "http://www.securityfocus.com/bid/105647"
         }
      ]
   }
}
