{
   "CVE_data_meta" : {
      "ASSIGNER" : "kurt@seifried.org",
      "DATE_ASSIGNED" : "2018-09-14T14:17:47.506460",
      "DATE_REQUESTED" : "2018-08-30T11:34:18",
      "ID" : "CVE-2018-1000802",
      "REQUESTER" : "kochukov.ma@gmail.com",
      "STATE" : "PUBLIC"
   },
   "affects" : {
      "vendor" : {
         "vendor_data" : [
            {
               "product" : {
                  "product_data" : [
                     {
                        "product_name" : "Python (CPython)",
                        "version" : {
                           "version_data" : [
                              {
                                 "version_value" : "2.7"
                              }
                           ]
                        }
                     }
                  ]
               },
               "vendor_name" : "Python Software Foundation"
            }
         ]
      }
   },
   "data_format" : "MITRE",
   "data_type" : "CVE",
   "data_version" : "4.0",
   "description" : {
      "description_data" : [
         {
            "lang" : "eng",
            "value" : "Python Software Foundation Python (CPython) version 2.7 contains a CWE-77: Improper Neutralization of Special Elements used in a Command ('Command Injection') vulnerability in shutil module (make_archive function) that can result in Denial of service, Information gain via injection of arbitrary files on the system or entire drive. This attack appear to be exploitable via Passage of unfiltered user input to the function. This vulnerability appears to have been fixed in after commit add531a1e55b0a739b0f42582f1c9747e5649ace."
         }
      ]
   },
   "problemtype" : {
      "problemtype_data" : [
         {
            "description" : [
               {
                  "lang" : "eng",
                  "value" : "CWE-77: Improper Neutralization of Special Elements used in a Command ('Command Injection')"
               }
            ]
         }
      ]
   },
   "references" : {
      "reference_data" : [
         {
            "name" : "[debian-lts-announce] 20180925 [SECURITY] [DLA 1519-1] python2.7 security update",
            "refsource" : "MLIST",
            "url" : "https://lists.debian.org/debian-lts-announce/2018/09/msg00030.html"
         },
         {
            "name" : "[debian-lts-announce] 20180926 [SECURITY] [DLA 1520-1] python3.4 security update",
            "refsource" : "MLIST",
            "url" : "https://lists.debian.org/debian-lts-announce/2018/09/msg00031.html"
         },
         {
            "name" : "https://mega.nz/#!JUFiCC4R!mq-jQ8ySFwIhX6WMDujaZuNBfttDVt7DETlfOIQE1ig",
            "refsource" : "MISC",
            "url" : "https://mega.nz/#!JUFiCC4R!mq-jQ8ySFwIhX6WMDujaZuNBfttDVt7DETlfOIQE1ig"
         },
         {
            "name" : "https://bugs.python.org/issue34540",
            "refsource" : "CONFIRM",
            "url" : "https://bugs.python.org/issue34540"
         },
         {
            "name" : "https://github.com/python/cpython/pull/8985",
            "refsource" : "CONFIRM",
            "url" : "https://github.com/python/cpython/pull/8985"
         },
         {
            "name" : "https://github.com/python/cpython/pull/8985/commits/add531a1e55b0a739b0f42582f1c9747e5649ace",
            "refsource" : "CONFIRM",
            "url" : "https://github.com/python/cpython/pull/8985/commits/add531a1e55b0a739b0f42582f1c9747e5649ace"
         },
         {
            "name" : "DSA-4306",
            "refsource" : "DEBIAN",
            "url" : "https://www.debian.org/security/2018/dsa-4306"
         },
         {
            "name" : "USN-3817-1",
            "refsource" : "UBUNTU",
            "url" : "https://usn.ubuntu.com/3817-1/"
         },
         {
            "name" : "USN-3817-2",
            "refsource" : "UBUNTU",
            "url" : "https://usn.ubuntu.com/3817-2/"
         }
      ]
   }
}
